{
 "title": "FastAPI Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "CPU Usage (per container)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='ns-website-db', container!='POD'}[5m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Request Errors (4xx & 5xx)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~'4..|5..'}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Memory Usage (per container)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace='ns-website-db', container!='POD'}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_latency_seconds_sum[5m]) / rate(http_request_latency_seconds_count[5m])",
     "legendFormat": "Latency (s)"
    }
   ]
  }
 ]
}