name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          DIGITALOCEAN_USERNAME: ${{ github.actor }}  # Placeholder, DigitalOcean only requires the token for now we take the github username
        run: |
          echo "${DIGITALOCEAN_ACCESS_TOKEN}" | docker login registry.digitalocean.com -u "${DIGITALOCEAN_USERNAME}" --password-stdin

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/devops-cicd/fast-api:latest .

      # Push Docker Image
      - name: Push Docker image to DigitalOcean
        run: |
          docker push registry.digitalocean.com/devops-cicd/fast-api:latest


      # Trigger Kubernetes Rollout Restart      
      - name: Set up Kubeconfig
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment/website -n ns-website-db
