name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Stap 2: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Pas aan naar de juiste Python-versie
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Stap 2: Log in to DigitalOcean Container Registry
      - name: Log in to DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          DIGITALOCEAN_USERNAME: ${{ github.actor }}  # Placeholder, DigitalOcean only requires the token for now we take the github username
        run: |
          echo "${DIGITALOCEAN_ACCESS_TOKEN}" | docker login registry.digitalocean.com -u "${DIGITALOCEAN_USERNAME}" --password-stdin

      # Stap 3: Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/devops-cicd/fast-api:latest .

      # Stap 4: Push Docker Image
      - name: Push Docker image to DigitalOcean
        run: |
          docker push registry.digitalocean.com/devops-cicd/fast-api:latest